_target_: src.nn_models.litmodels.BaseLitModel

model:
  _target_: timm.models.resnet18
  pretrained: true
  num_classes: 3

loss_fn: 
  _target_: torch.nn.CrossEntropyLoss

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.003
  weight_decay: 0.0001

scheduler:
  _target_: torch.optim.lr_scheduler.OneCycleLR
  _partial_: true
  max_lr: 0.001
  pct_start: 0.1
  total_steps: 1250
  div_factor: 10
  final_div_factor: 100

scheduler_interval: "step"

# compile model for faster training with pytorch 2.0
compile: true